name = "client-portal"
main = "portal-worker.js"
compatibility_date = "2025-05-01"

[assets]
directory = "./portal-dist"
binding = "ASSETS"

[vars]
ADMIN_EMAILS = "innovation@thereelrecipe.com,mira.samirr1@gmail.com,aliaasayed373@gmail.com,kenzy8856@gmail.com,habibamohamed0611@gmail.com"
SUPER_ADMIN_EMAILS = "innovation@thereelrecipe.com"
DEV_EMAIL = "innovation@thereelrecipe.com"
